### ISSUE TITLE
"Load Latest Event Data" gives nothing but a bunch of placeholder Pikachus

### ISSUE THREAD

**Issue by SadisticMystic** [SteveCookTU/sv_raid_lookup#2]
I suspect this has to do with the new data structure rollout GF created to prevent a repeat of the Bad Egg scenario--they now push out two files for raids: a "raid_enemy_array" that has nothing but these dummy entries, interpreted as Pikachu, that never actually spawn in the overworld, and a new "raid\_enemy\_array\_1\_3\_0" file (and similar for other files with corresponding \_1\_3\_0 versions) that only the new 1.3 patch knows to be aware of. The event parser should start looking at the new file.

**Comment by SteveCookTU** [comment]
Hi there! The source it pulls from updates every half hour I believe to get whatever event is currently live in-game. There is a chance the automated process may be down. The placeholder data they host when no event is live is just a bunch of Pikachu

**Comment by SteveCookTU** [comment]
Looks like the file structure didn't change and it's only the names. I'm not sure if this will continue for future updates or just this one as these 2 pokemon are the only ones version dependent as of right now.

For now, you can download the files from the repository it gets the files from and drag and drop them into the page to load them.

**Comment by SadisticMystic** [comment]
The same behavior was still observable with Inteleon, which came after 1.3 but was not version-exclusive.

**Comment by SteveCookTU** [comment]
> The same behavior was still observable with Inteleon, which came after 1.3 but was not version-exclusive.

Oh ok, didn't know that. I'll update it to use those files then by default. Thank you again for reporting this!
