### ISSUE TITLE
Displayed stats and type are incorrect for Pokemon above #916

### ISSUE THREAD

**Issue by SadisticMystic** [SteveCookTU/sv_raid_lookup#3]
If you click on the raid details for, say, Annihilape--it says the type is Grass/Psychic with stats of 90 - 130 - 88 - 70 - 108 - 104. Of course, those aren't its actual stats, they're the stats of Iron Leaves. Baxcalibur claims to be mono-grass with 50 - 62 - 40 - 62 - 40 - 50 (the stats of Capsakid), and so on. Pokemon that already existed prior to SV have their correct stats and type shown.

Based on the particular transformations involved, this is a case of reading in an index number ( https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_index_number_(Generation_IX) ) then interpreting it directly as a national dex number to get the Pokemon's stats.

**Comment by SteveCookTU** [comment]
We did discover this awhile back for SV and I guess I never updated it to use the correct number. Thank you for pointing this out!

**Comment by SteveCookTU** [comment]
Fixed in [89984bd](https://github.com/SteveCookTU/sv_raid_lookup/commit/89984bd4157e3fd8c11ec285c669ac10248dafdd)
