### ISSUE TITLE
Update event data links

### ISSUE THREAD

**Issue by Flametix** [SteveCookTU/sv_raid_lookup#6]
Currently the Latest Event Data button has just been showing the placeholder Pikachu even during raid events. I believe the file links from the citrusbolt.net page should be updated to refer to the versions ending in 2_0_0 instead of 1_3_0 for the ones currently being updated.
https://github.com/SteveCookTU/sv_raid_lookup/blob/9b65ed142d1c95ca4e7484021fd2434f24d23a85/src/side_panel.rs#L41

**Comment by SteveCookTU** [comment]
Thank you for pointing this out! I will update this shortly.

**Comment by SteveCookTU** [comment]
Fixed in #7
