### ISSUE TITLE
Raid times all showing up as 0s for 2-5 stars

### ISSUE THREAD

**Issue by Flametix** [SteveCookTU/sv_raid_lookup#9]
Clicking on the 2 to 5 star raids from each region seems to show the total raid time as well as any of their time-based actions also showing as always being 0s.
![image](https://github.com/SteveCookTU/sv_raid_lookup/assets/44883711/d1bc895b-b07b-45b6-83d4-5918a7c977f8)

1 star and 6 star raids seem to show time valuse as normal.
![image](https://github.com/SteveCookTU/sv_raid_lookup/assets/44883711/d6ddf2c2-9004-4646-9ff0-b3c7428261f7)

**Comment by SteveCookTU** [comment]
When we originally extracted the data from the game, we noticed a lot of 0 values, specifically for 2-5 as you mentioned. We never did more digging but there is a good chance it uses the same raid time as 1 or 6 star. I never actually took the time to time the battle and determine the actual length. Without running any decompilation or testing, it wont be known.

If you have the times on hand, I will gladly update them as the defaults for 0s values. I believe this also goes for the 0s moves where they are at a certain default time ( probably 45s)

**Comment by Flametix** [comment]
Serebii shows the time based actions as a percentage of time remaining, so those would probably be fixed on their own when you add the total time for these raids.

For reference, I timed the 3 different stars available to me from 3 different regions to be sure, and it seems like they do last for about 5 minutes/300 seconds as the default in these cases.

3 star Fire Gothorita in Paldea: 5 minutes (300s) Reflect used after 30 seconds/90% time remaining, and at 4:30 saw the tremendous energy warning which is likely at 10% time remaining (same for the rest).

4 star Rock Dusclops in Kitakami: 5 minutes (300s). Stat reset after 2 minutes/60% time remaining. Shield went up after 3 minutes/40% time remaining.

5 star Rock Reuniclus in Blueberry: 5 minutes (300s). Shield went up after about 3.5 minutes/30% time remaining.

**Comment by SteveCookTU** [comment]
Just tested as well and I'm seeing 300s for the raid time which matches the 1 star raids.

The percentage is actually how I'm calculating the times. Updating the raid time and such to 300s should fix everything else.

**Comment by SteveCookTU** [comment]
Should be fixed in the latest commit. Let me know if you see any discrepancies.

**Comment by Flametix** [comment]
Everything looks as expected. Thanks for the quick update!
